blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('post/new/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<slug:slug>/comment/', views.add_comment, name='add_comment'),
    path('bloggers/', views.BloggerListView.as_view(), name='blogger_list'),
    path('blogger/<str:username>/', views.BloggerDetailView.as_view(), name='blogger_detail'),
    path('profile/edit/', views.BloggerProfileUpdateView.as_view(), name='profile_edit'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('tag/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('signup/', views.signup, name='signup'),
]

gilded_pen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category_detail', args=[self.slug])

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', args=[self.slug])

class BloggerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

    def get_absolute_url(self):
        return reverse('blog:blogger_detail', args=[self.user.username])

class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='posts')
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts')

    class Meta:
        ordering = ['-published_date']

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return f'Comment by {self.author} on {self.post.title[:75]}'

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.text import slugify
from .models import Comment, Post, BloggerProfile

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Write your comment here...'
            }),
        }
        labels = {
            'text': 'Comment'
        }

class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email'
        })
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add Bootstrap classes to all fields
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter post title'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 10,
                'placeholder': 'Write your blog post here...'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control'
            }),
            'tags': forms.SelectMultiple(attrs={
                'class': 'form-control'
            })
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if self.instance.pk is None:  # Only for new posts
            slug = slugify(title)
            if Post.objects.filter(slug=slug).exists():
                raise forms.ValidationError('A post with this title already exists. Please choose a different title.')
        return title

    def save(self, commit=True):
        post = super().save(commit=False)
        post.slug = slugify(post.title)
        if commit:
            post.save()
            self.save_m2m()  # Save many-to-many relationships (tags)
        return post

class BloggerProfileForm(forms.ModelForm):
    class Meta:
        model = BloggerProfile
        fields = ['bio', 'profile_picture']
        widgets = {
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Write something about yourself...'
            }),
            'profile_picture': forms.FileInput(attrs={
                'class': 'form-control'
            })
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login
from django.contrib import messages
from django.utils import timezone
from .models import Post, BloggerProfile, Category, Tag, Comment
from .forms import CommentForm, SignUpForm, PostForm, BloggerProfileForm

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'blog/home.html'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'The Gilded Pen'
        return context

class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'blog/index.html'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'About The Gilded Pen'
        return context

class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 5
    ordering = ['-published_date']
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        return context

class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all()
        context['comment_form'] = CommentForm()
        return context

class BloggerListView(LoginRequiredMixin, ListView):
    model = BloggerProfile
    template_name = 'blog/blogger_list.html'
    context_object_name = 'bloggers'
    login_url = 'login'
    redirect_field_name = 'next'

class BloggerDetailView(LoginRequiredMixin, DetailView):
    model = BloggerProfile
    template_name = 'blog/blogger_detail.html'
    context_object_name = 'blogger'
    slug_field = 'user__username'
    slug_url_kwarg = 'username'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(author=self.object.user).order_by('-published_date')
        return context

class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = 'blog/category_detail.html'
    context_object_name = 'category'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.posts.all().order_by('-published_date')
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        return context

class TagDetailView(LoginRequiredMixin, DetailView):
    model = Tag
    template_name = 'blog/tag_detail.html'
    context_object_name = 'tag'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.object.posts.all().order_by('-published_date')
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    login_url = 'login'
    redirect_field_name = 'next'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = timezone.now()
        messages.success(self.request, 'Your blog post has been created successfully!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_queryset(self):
        # Only allow users to edit their own posts
        return Post.objects.filter(author=self.request.user)

    def form_valid(self, form):
        messages.success(self.request, 'Your blog post has been updated successfully!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_list')
    login_url = 'login'
    redirect_field_name = 'next'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

class BloggerProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = BloggerProfile
    form_class = BloggerProfileForm
    template_name = 'blog/blogger_form.html'
    login_url = 'login'
    redirect_field_name = 'next'

    def get_object(self, queryset=None):
        return self.request.user.bloggerprofile

    def get_success_url(self):
        return reverse_lazy('blog:blogger_detail', kwargs={'username': self.request.user.username})

@login_required(login_url='login')
def add_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', slug=post.slug)
    
    return redirect('blog:post_detail', slug=post.slug)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            BloggerProfile.objects.create(user=user)
            login(request, user)
            messages.success(request, 'Welcome to The Gilded Pen! Your account has been created successfully.')
            return redirect('blog:home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}The Gilded Pen{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        body {
            font-family: 'Georgia', serif;
            line-height: 1.6;
            background-color: #f8f9fa;
        }
        .navbar-brand {
            font-family: 'Playfair Display', serif;
            font-size: 1.8rem;
        }
        .sidebar {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .post-card {
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
            padding: 20px;
        }
        .post-title {
            color: #2c3e50;
            font-family: 'Playfair Display', serif;
        }
        .post-meta {
            color: #7f8c8d;
            font-size: 0.9rem;
        }
        .comment-section {
            margin-top: 30px;
        }
        .comment {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .alert {
            margin-bottom: 20px;
        }
        .invalid-feedback {
            display: block;
        }

        /* Post Card Styles */
        .post-card {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }

        .post-title {
            color: #2c3e50;
            margin-bottom: 1rem;
        }

        .post-title a {
            color: inherit;
            text-decoration: none;
        }

        .post-title a:hover {
            color: #3498db;
        }

        .post-meta {
            color: #7f8c8d;
            font-size: 0.9rem;
        }

        .post-meta a {
            color: #3498db;
        }

        .post-content {
            color: #34495e;
            line-height: 1.6;
        }

        /* Sidebar Styles */
        .sidebar-widget {
            margin-bottom: 2rem;
        }

        .widget-title {
            color: #2c3e50;
            font-size: 1.25rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #3498db;
        }

        .tag-cloud {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
        }

        .tag-cloud .badge {
            font-size: 0.9rem;
            padding: 0.5rem 0.75rem;
            transition: all 0.2s ease;
        }

        .tag-cloud .badge:hover {
            background-color: #3498db !important;
            transform: translateY(-1px);
        }

        .list-group-item {
            border: none;
            border-radius: 4px !important;
            margin-bottom: 0.25rem;
            transition: all 0.2s ease;
        }

        .list-group-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
        }

        /* Navigation Styles */
        .navbar {
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        /* Button Styles */
        .btn-primary {
            background-color: #3498db;
            border-color: #3498db;
        }

        .btn-primary:hover {
            background-color: #2980b9;
            border-color: #2980b9;
        }

        .btn-outline-primary {
            color: #3498db;
            border-color: #3498db;
        }

        .btn-outline-primary:hover {
            background-color: #3498db;
            border-color: #3498db;
        }

        /* Badge Styles */
        .badge {
            font-weight: 500;
        }

        .badge.bg-secondary {
            background-color: #7f8c8d !important;
        }

        .badge.bg-primary {
            background-color: #3498db !important;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:home' %}">The Gilded Pen</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:index' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blogger_list' %}">Bloggers</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link">Welcome, {{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'logout' %}" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn nav-link">Logout</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}{% endblock %}
            </div>

            <div class="col-md-4">
                {% if user.is_authenticated %}
                    <div class="sidebar-widget post-card mb-4">
                        <h4 class="widget-title">Quick Actions</h4>
                        <div class="d-grid gap-2">
                            <a href="{% url 'blog:post_create' %}" class="btn btn-primary">
                                <i class="fas fa-plus"></i> Create New Post
                            </a>
                            <a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary">
                                <i class="fas fa-list"></i> View All Posts
                            </a>
                        </div>
                    </div>

                    {% if categories %}
                        <div class="sidebar-widget post-card mb-4">
                            <h4 class="widget-title">Categories</h4>
                            <div class="list-group">
                                {% for category in categories %}
                                    <a href="{% url 'blog:category_detail' category.slug %}" 
                                       class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                        {{ category.name }}
                                        <span class="badge bg-primary rounded-pill">{{ category.posts.count }}</span>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}

                    {% if tags %}
                        <div class="sidebar-widget post-card mb-4">
                            <h4 class="widget-title">Popular Tags</h4>
                            <div class="tag-cloud">
                                {% for tag in tags %}
                                    <a href="{% url 'blog:tag_detail' tag.slug %}" 
                                       class="badge bg-secondary text-decoration-none me-1 mb-1">
                                        {{ tag.name }} ({{ tag.posts.count }})
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

    <footer class="bg-dark text-light mt-5">
        <div class="container py-4">
            <div class="row">
                <div class="col-md-6">
                    <h5>The Gilded Pen</h5>
                    <p>A place for thoughtful writing and engaging discussions.</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p>&copy; {% now "Y" %} The Gilded Pen. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blogger_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ blogger.user.username }}'s Profile - The Gilded Pen{% endblock %}

{% block content %}
<div class="post-card mb-4">
    <div class="text-center mb-4">
        {% if blogger.profile_picture %}
            <img src="{{ blogger.profile_picture.url }}" alt="{{ blogger.user.username }}" class="rounded-circle mb-3" style="width: 150px; height: 150px; object-fit: cover;">
        {% else %}
            <div class="rounded-circle bg-secondary text-white d-flex align-items-center justify-content-center mx-auto mb-3" style="width: 150px; height: 150px;">
                <i class="fas fa-user fa-4x"></i>
            </div>
        {% endif %}
        
        <h1 class="mb-2">{{ blogger.user.username }}</h1>
        
        {% if user == blogger.user %}
            <a href="{% url 'blog:profile_edit' %}" class="btn btn-primary btn-sm">
                <i class="fas fa-edit"></i> Edit Profile
            </a>
        {% endif %}
    </div>

    <div class="mb-4">
        <h2 class="h4 mb-3">About</h2>
        {% if blogger.bio %}
            <p>{{ blogger.bio }}</p>
        {% else %}
            <p class="text-muted">No bio available.</p>
        {% endif %}
    </div>
</div>

<div class="post-card">
    <h2 class="h4 mb-4">Posts by {{ blogger.user.username }}</h2>
    
    {% if posts %}
        <div class="list-group">
            {% for post in posts %}
                <a href="{% url 'blog:post_detail' post.slug %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small class="text-muted">{{ post.published_date|date:"F j, Y" }}</small>
                    </div>
                    {% if post.category %}
                        <small class="text-muted">
                            <i class="fas fa-folder"></i> {{ post.category.name }}
                        </small>
                    {% endif %}
                    {% if post.comments.count %}
                        <small class="text-muted ms-3">
                            <i class="fas fa-comments"></i> {{ post.comments.count }} Comments
                        </small>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p>No posts available.</p>
    {% endif %}
</div>

<div class="mt-4">
    <a href="{% url 'blog:blogger_list' %}" class="btn btn-outline-primary">
        <i class="fas fa-arrow-left"></i> Back to Bloggers
    </a>
</div>
{% endblock %}

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ category.name }} - The Gilded Pen{% endblock %}

{% block content %}
<div class="category-header mb-4">
    <h1 class="mb-2">Category: {{ category.name }}</h1>
    {% if category.description %}
        <p class="lead">{{ category.description }}</p>
    {% endif %}
</div>

{% if posts %}
    {% for post in posts %}
        <article class="post-card">
            <h2 class="post-title">
                <a href="{% url 'blog:post_detail' post.slug %}" class="text-decoration-none">{{ post.title }}</a>
            </h2>
            <div class="post-meta mb-3">
                <span><i class="fas fa-user"></i> By <a href="{% url 'blog:blogger_detail' post.author.username %}" class="text-decoration-none">{{ post.author.username }}</a></span>
                <span class="mx-2">|</span>
                <span><i class="fas fa-calendar"></i> {{ post.published_date|date:"F j, Y" }}</span>
                {% if post.author == user %}
                    <span class="mx-2">|</span>
                    <a href="{% url 'blog:post_edit' post.slug %}" class="text-decoration-none">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                {% endif %}
            </div>
            <div class="post-content">
                {{ post.content|truncatewords:50 }}
            </div>
            <div class="mt-3">
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:tag_detail' tag.slug %}" class="badge bg-secondary text-decoration-none me-1">{{ tag.name }}</a>
                {% endfor %}
            </div>
            <div class="mt-3">
                <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-outline-primary btn-sm">Read More</a>
                <span class="ms-3"><i class="fas fa-comments"></i> {{ post.comments.count }} Comments</span>
            </div>
        </article>
    {% endfor %}
{% else %}
    <div class="post-card">
        <p class="text-center">No posts in this category yet. 
            <a href="{% url 'blog:post_create' %}" class="text-decoration-none">Create the first post!</a>
        </p>
    </div>
{% endif %}

<div class="mt-4">
    <a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary">
        <i class="fas fa-arrow-left"></i> Back to All Posts
    </a>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}Welcome to The Gilded Pen{% endblock %}

{% block content %}
<div class="text-center mb-5">
    <h1 class="display-4">Welcome to The Gilded Pen</h1>
    <p class="lead">A space where words come to life and stories find their voice.</p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="post-card">
            <h2>About Our Blog</h2>
            <p>The Gilded Pen is a community of writers, thinkers, and storytellers. Here, we celebrate the art of writing and the power of words to inspire, educate, and connect.</p>
            <p>Whether you're a seasoned writer or just beginning your journey, you'll find a welcoming space to share your thoughts and engage with others.</p>
            <div class="text-center mt-4">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary">Explore Our Posts</a>
                <a href="{% url 'blog:blogger_list' %}" class="btn btn-outline-primary ms-2">Meet Our Writers</a>
            </div>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-6">
        <div class="post-card h-100">
            <h3><i class="fas fa-feather-alt"></i> For Writers</h3>
            <p>Share your stories, insights, and expertise with our growing community. Join us as a contributor and let your voice be heard.</p>
            {% if user.is_authenticated %}
                <p>Welcome back! Continue sharing your thoughts with our community.</p>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-outline-primary">Login to Contribute</a>
            {% endif %}
        </div>
    </div>
    <div class="col-md-6">
        <div class="post-card h-100">
            <h3><i class="fas fa-book-reader"></i> For Readers</h3>
            <p>Discover thoughtful articles, engaging stories, and diverse perspectives from our community of writers.</p>
            <a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary">Start Reading</a>
        </div>
    </div>
</div>
{% endblock %}